version: "3.5"

services:
  nextyce-api:
    build:
      context: ./nextyce-api
      dockerfile: run.Dockerfile
    ports:
      - 5000:80
    volumes:
      - ./nextyce-api/src/NextyceApi:/app

  nextyce-ui:
    build: ./nextyce-ui
    ports:
      - "4200:4200" # Port mapping
    volumes:
      - "./nextyce-ui:/usr/src/app"